type User {
  _id: ID!
  name: String!
  email: String!
  gender: String
  ra: String
  birthday: Date
  password: String!
  admin: Boolean!
}

type Query {
  users: [User!]!
  user(id: ID!): User!
  userLogin(ra: String!, password: String!): userOrError
}

union userOrError = Error | User

type Error {
  message: String
}

input UserInput {
  name: String!
  email: String!
  gender: String
  ra: String
  birthday: Date
  password: String!
  admin: Boolean!
}
type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: ID, data: UserInput): User!
  deleteUser(id: ID): Boolean
}
